/**
 * Generate `docs/module-graph.md` from in-repo `peerDependencies`, the canonical
 * runtime edges. The deterministic output groups packages by directory and
 * renders both Mermaid and a dependency table; `--check` verifies freshness.
 */

import { resolve } from 'node:path'
import { readFileSync, writeFileSync } from 'node:fs'
import {
  collectPackageGraph,
  escapeMermaidLabel as escLabel,
  graphNodeId as nodeId,
  type PackageGraphNode,
} from './package-graph.ts'

const root = resolve(import.meta.dirname, '..')
const OUT = 'docs/module-graph.md'
const OUT_ZH = 'docs/module-graph.zh.md'
type Pkg = PackageGraphNode

const GROUP_ORDER = [
  'util',
  'llm',
  'core',
  'goal',
  'bash',
  'fs',
  'skill',
  'compact',
  'subagent',
  'web',
  'spill',
  'timeout',
  'todo',
  'plan',
  'cordis',
  'hooks',
  'session-persistence',
  'session-query',
  'session-title',
  'support',
  'acp',
  'ui',
]

function packageLink(pkg: Pkg): string {
  return `[\`${pkg.short}\`](../${pkg.rel})`
}

/** Render the full docs/module-graph.md content (pure, deterministic). */
function render(pkgs: Pkg[]): string {
  const edges: string[] = []
  for (const p of pkgs) {
    for (const d of p.deps) edges.push(`  ${nodeId('pkg', p.short)} --> ${nodeId('pkg', d)}`)
  }
  const byShort = new Map(pkgs.map(pkg => [pkg.short, pkg]))
  const groups = [...new Set(pkgs.map(pkg => pkg.group))].sort((a, b) => {
    const ia = GROUP_ORDER.indexOf(a)
    const ib = GROUP_ORDER.indexOf(b)
    const na = ia === -1 ? Number.MAX_SAFE_INTEGER : ia
    const nb = ib === -1 ? Number.MAX_SAFE_INTEGER : ib
    return na - nb || a.localeCompare(b)
  })
  const groupBlocks: string[] = []
  for (const group of groups) {
    groupBlocks.push(`  subgraph ${nodeId('group', group)}["packages/${escLabel(group)}"]`)
    for (const pkg of pkgs.filter(p => p.group === group).sort((a, b) => a.short.localeCompare(b.short))) {
      groupBlocks.push(`    ${nodeId('pkg', pkg.short)}["${escLabel(pkg.short)}"]`)
    }
    groupBlocks.push('  end')
  }
  const rows = pkgs.map((p) => {
    const deps = p.deps.length ? p.deps.map((d) => {
      const dep = byShort.get(d)
      return dep ? packageLink(dep) : `\`${d}\``
    }).join(', ') : '—'
    return `| ${packageLink(p)} | \`${p.group}\` | ${deps} |`
  })
  return [
    '<!-- Generated by scripts/gen-module-graph.ts — do not edit by hand.',
    '     Run `pnpm run gen-module-graph` to regenerate. -->',
    '',
    '# Module dependency graph',
    '',
    'Inter-package dependencies among the `@deepseek-ai/dsh-*` harness packages, derived from each package\'s `peerDependencies` (the canonical runtime-dependency signal) and grouped by the `packages/<group>/<pkg>` hierarchy. An edge `a --> b` means package `a` depends on package `b`. Names have the `@deepseek-ai/dsh-` prefix stripped.',
    '',
    '```mermaid',
    'flowchart TD',
    ...groupBlocks,
    ...edges,
    '```',
    '',
    '| Package | Group | Depends on |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ].join('\n')
}

/** Render the reviewed Chinese counterpart over the same generated graph body. */
function renderZh(pkgs: Pkg[]): string {
  const english = render(pkgs)
  const graphStart = english.indexOf('```mermaid')
  if (graphStart < 0) throw new Error('generated module graph is missing its Mermaid block')
  const graph = english.slice(graphStart)
    .replace('| Package | Group | Depends on |', '| 包 | 分组 | 依赖 |')
  return [
    '<!-- 由 scripts/gen-module-graph.ts 生成，请勿手工编辑。',
    '     运行 `pnpm run gen-module-graph` 重新生成。 -->',
    '',
    '# 模块依赖关系图',
    '',
    '[English](module-graph.md) | 中文',
    '',
    '`@deepseek-ai/dsh-*` harness 包之间的依赖关系。该关系图根据各包的 `peerDependencies`（规范的运行时依赖信号）生成，并按 `packages/<group>/<pkg>` 层级分组。边 `a --> b` 表示包 `a` 依赖包 `b`。名称中的 `@deepseek-ai/dsh-` 前缀已移除。',
    '',
    graph,
  ].join('\n')
}

const content = render(collectPackageGraph(root, GROUP_ORDER, 'gen-module-graph'))
const contentZh = renderZh(collectPackageGraph(root, GROUP_ORDER, 'gen-module-graph'))

if (process.argv.includes('--check')) {
  for (const [path, expected] of [[OUT, content], [OUT_ZH, contentZh]] as const) {
    let committed: string | null = null
    try {
      committed = readFileSync(resolve(root, path), 'utf8')
    } catch {
      // A missing artifact is the expected read failure. Any read failure has
      // the same remedy here—regenerate—so it is reported as stale below.
      committed = null
    }
    if (committed !== expected) {
      console.error(`gen-module-graph: ${path} is stale. Run \`pnpm run gen-module-graph\` and commit ${path}.`)
      process.exit(1)
    }
  }
  console.log(`gen-module-graph: ${OUT} and ${OUT_ZH} are up to date.`)
  process.exit(0)
}

writeFileSync(resolve(root, OUT), content)
writeFileSync(resolve(root, OUT_ZH), contentZh)
console.log(`gen-module-graph: wrote ${OUT} and ${OUT_ZH}.`)
