const PHYSICAL_OPERATOR_STYLES = `
:root { --dsh-physical-popup-underlay:#fff } body[data-ds-dark-theme] { --dsh-physical-popup-underlay:#151517 }
.dshDesktopResidentAction { display:inline-flex;align-items:center;gap:6px;box-sizing:border-box;height:26px;padding:0 9px;border:1px solid var(--dsw-alias-border-l2);border-radius:999px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-secondary);cursor:pointer;font:inherit;font-size:10px;font-weight:600;white-space:nowrap }.dshDesktopResidentAction:hover { background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary) }
.dshDesktopResidentDot { display:inline-block;flex:none;width:8px;height:8px;border-radius:50%;background:#7d8799;box-shadow:0 0 0 2px color-mix(in srgb,#7d8799 20%,transparent) }.dshDesktopResidentAction[data-status="running"] .dshDesktopResidentDot,.dshDesktopResidentSession[data-health="ok"] .dshDesktopResidentDot,.dshDesktopResidentProvider[data-ok] .dshDesktopResidentDot { background:#34c759;box-shadow:0 0 0 2px color-mix(in srgb,#34c759 20%,transparent) }.dshDesktopResidentAction[data-status="warn"] .dshDesktopResidentDot,.dshDesktopResidentSession[data-health="degraded"] .dshDesktopResidentDot { background:#f5a623 }.dshDesktopResidentAction[data-status="error"] .dshDesktopResidentDot,.dshDesktopResidentSession[data-health="unavailable"] .dshDesktopResidentDot { background:#ff453a }
.dshDesktopResidentBackdrop { position:fixed;z-index:2147483000;inset:0;display:flex;align-items:center;justify-content:center;padding:32px;background:rgb(5 8 14/58%);backdrop-filter:blur(8px) }.dshDesktopResidentPanel { box-sizing:border-box;width:min(1120px,calc(100vw - 64px));height:min(720px,calc(100vh - 64px));overflow:hidden;border:1px solid var(--dsw-alias-border-l1);border-radius:18px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);box-shadow:0 24px 80px rgb(0 0 0/45%) }.dshDesktopResidentPanel>header { display:flex;align-items:flex-start;justify-content:space-between;gap:24px;padding:20px 24px 16px;border-bottom:1px solid var(--dsw-alias-border-l2) }.dshDesktopResidentPanel h2,.dshDesktopResidentPanel h3,.dshDesktopResidentPanel p { margin:0 }.dshDesktopResidentPanel h2 { font-size:20px;line-height:28px }.dshDesktopResidentPanel h3 { margin-bottom:10px;font-size:12px;letter-spacing:.04em;text-transform:uppercase }.dshDesktopResidentPanel>header p,.dshDesktopResidentPanel>header small,.dshDesktopResidentEmpty { display:block;margin-top:3px;color:var(--dsw-alias-label-secondary);font-size:12px }.dshDesktopResidentPanel>header>button { width:32px;height:32px;border:0;border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);cursor:pointer;font-size:22px }
.dshDesktopResidentGrid { display:grid;grid-template-columns:1.05fr 1.25fr 1fr;height:calc(100% - 82px);min-height:0 }.dshDesktopResidentColumn { min-width:0;overflow:auto;padding:18px;border-right:1px solid var(--dsw-alias-border-l2) }.dshDesktopResidentColumn:last-child { border-right:0 }.dshDesktopResidentProviders { display:grid;gap:8px;margin-bottom:22px }.dshDesktopResidentProvider { display:grid;grid-template-columns:8px minmax(0,1fr) auto;align-items:center;gap:9px;padding:10px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1) }.dshDesktopResidentProvider strong,.dshDesktopResidentProvider small { display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap }.dshDesktopResidentProvider small,.dshDesktopResidentProvider em { color:var(--dsw-alias-label-secondary);font-size:9px }.dshDesktopResidentProvider em { font-style:normal }
.dshDesktopResidentHelp { display:grid;gap:8px;color:var(--dsw-alias-label-secondary);font-size:11px;line-height:16px }.dshDesktopResidentHelp code { display:block;padding:8px 10px;overflow-wrap:anywhere;border-radius:8px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);font-size:10px }
.dshDesktopResidentSession { display:grid;grid-template-columns:8px minmax(0,1fr) auto;align-items:center;gap:9px;width:100%;margin-bottom:8px;padding:10px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);cursor:pointer;text-align:left }.dshDesktopResidentSession[data-selected] { border-color:#f5a623;box-shadow:0 0 0 1px color-mix(in srgb,#f5a623 40%,transparent) }.dshDesktopResidentSession strong,.dshDesktopResidentSession small,.dshDesktopResidentSession em { display:block;max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap }.dshDesktopResidentSession small,.dshDesktopResidentSession em { color:var(--dsw-alias-label-secondary);font-size:9px }.dshDesktopResidentSession em { font-style:normal;text-align:right }
.dshDesktopResidentEvents ol { margin:0;padding:0;list-style:none }.dshDesktopResidentEvents li { display:grid;grid-template-columns:78px minmax(0,1fr);gap:3px 8px;padding:10px 0;border-bottom:1px solid var(--dsw-alias-border-l2);font-size:10px }.dshDesktopResidentEvents time { grid-row:1/3;color:var(--dsw-alias-label-secondary) }.dshDesktopResidentEvents li span { color:var(--dsw-alias-label-secondary) }.dshDesktopResidentError { margin:12px 24px 0;padding:9px 12px;border:1px solid color-mix(in srgb,#ff453a 45%,transparent);border-radius:8px;background:color-mix(in srgb,#ff453a 12%,transparent);color:#ff6961;font-size:11px }
.dshDesktopOperatorRoutingWrap { position:relative;display:inline-flex;align-items:center;min-width:0 }.dshDesktopOperatorRoutingChip { display:inline-flex;align-items:center;gap:2px;max-width:132px;height:26px;padding:0 5px 0 8px;border:0;border-radius:7px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer;font-size:11px;white-space:nowrap }.dshDesktopOperatorRoutingChip:hover:not(:disabled),.dshDesktopOperatorRoutingChip[aria-expanded="true"] { background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary) }.dshDesktopOperatorRoutingChip:disabled { cursor:default;opacity:.48 }.dshDesktopOperatorRoutingChip>span { overflow:hidden;text-overflow:ellipsis }
.dshDesktopOperatorStrategyBackdrop { position:fixed;z-index:2147482990;inset:0;background:transparent }.dshDesktopOperatorStrategyPanel { position:fixed;box-sizing:border-box;width:min(420px,calc(100vw - 24px));max-height:calc(100vh - 72px);overflow:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:14px;background:linear-gradient(var(--dsw-alias-bg-base,transparent),var(--dsw-alias-bg-base,transparent)),var(--dsh-physical-popup-underlay);color:var(--dsw-alias-label-primary);box-shadow:0 18px 54px rgb(0 0 0/38%) }.dshDesktopOperatorStrategyPanel>header { display:flex;align-items:flex-start;justify-content:space-between;gap:16px;padding:14px 16px 12px;border-bottom:1px solid var(--dsw-alias-border-l2) }.dshDesktopOperatorStrategyPanel>header div,.dshDesktopOperatorProfilePreferences>div { display:grid;gap:3px }.dshDesktopOperatorStrategyPanel strong { font-size:12px }.dshDesktopOperatorStrategyPanel small,.dshDesktopOperatorStrategyPanel p { margin:0;color:var(--dsw-alias-label-secondary);font-size:10px;line-height:15px }.dshDesktopOperatorStrategyPanel>header>button { flex:none;width:26px;height:26px;border:0;border-radius:7px;background:var(--dsw-alias-bg-layer-2);color:var(--dsw-alias-label-primary);cursor:pointer;font-size:18px }
.dshDesktopOperatorStrategyOptions { display:grid;gap:5px;padding:10px }.dshDesktopOperatorStrategyOptions>button { display:grid;grid-template-columns:14px minmax(0,1fr);align-items:start;gap:9px;width:100%;padding:9px 10px;border:1px solid transparent;border-radius:9px;background:transparent;color:var(--dsw-alias-label-primary);cursor:pointer;text-align:left }.dshDesktopOperatorStrategyOptions>button:hover:not(:disabled) { background:var(--dsw-alias-bg-layer-2) }.dshDesktopOperatorStrategyOptions>button[data-selected] { border-color:color-mix(in srgb,#f5a623 55%,transparent);background:color-mix(in srgb,#f5a623 10%,transparent) }.dshDesktopOperatorStrategyOptions>button:disabled { cursor:default;opacity:.58 }.dshDesktopOperatorStrategyOptions>button>span:last-child { display:grid;gap:2px }.dshDesktopOperatorStrategyRadio { box-sizing:border-box;width:12px;height:12px;margin-top:2px;border:1px solid var(--dsw-alias-label-tertiary);border-radius:50% }.dshDesktopOperatorStrategyOptions>button[data-selected] .dshDesktopOperatorStrategyRadio { border:3px solid #f5a623 }
.dshDesktopOperatorProfilePreferences { display:grid;gap:10px;margin:0 10px 10px;padding:12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1) }.dshDesktopOperatorProfilePreferences label { display:grid;grid-template-columns:minmax(0,1fr) minmax(150px,1.1fr);align-items:center;gap:12px;color:var(--dsw-alias-label-secondary);font-size:10px }.dshDesktopOperatorProfilePreferences select { min-width:0;height:30px;padding:0 8px;border:1px solid var(--dsw-alias-border-l1);border-radius:7px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);font-size:10px }.dshDesktopOperatorStrategyError { margin:0 12px 12px!important;padding:7px 9px;border-radius:7px;background:color-mix(in srgb,#ff453a 12%,transparent);color:#ff6961!important }
@media(max-width:900px){.dshDesktopResidentGrid{grid-template-columns:1fr;overflow:auto}.dshDesktopResidentColumn{overflow:visible;border-right:0;border-bottom:1px solid var(--dsw-alias-border-l2)}}
@media(max-width:640px){.dshDesktopResidentBackdrop{padding:8px}.dshDesktopResidentPanel{width:calc(100vw - 16px);height:calc(100vh - 16px)}.dshDesktopOperatorProfilePreferences label{grid-template-columns:1fr}}
`

/**
 * Install styles owned by the physical-operator client plugin.
 * @returns a disposer that removes the installed style element.
 */
export function installPhysicalOperatorStyles(): () => void {
  const style = document.createElement('style')
  style.dataset.plugin = '@deepseek-ai/dsh-ui-physical-operator'
  style.textContent = PHYSICAL_OPERATOR_STYLES
  document.head.appendChild(style)
  return () => { style.remove() }
}
